version: '3.8'

networks:
  myStackNetwork:
    driver: overlay

configs:
  haproxy_config:
    file: ./conf/haproxy-moodle.cfg

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local

services:
  mariadb:
    image: bitnami/mariadb:10.1
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb_data:/bitnami
    networks: 
      - myStackNetwork
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  moodle:
    image: bitnami/moodle:3
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - moodle_data:/bitnami
    networks: 
      - myStackNetwork
    restart: always
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr

  haproxy:
    image: haproxytech/haproxy-debian
    networks: 
      - myStackNetwork
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 8443
        protocol: tcp
        mode: host
    configs:
      - source: haproxy_config
        target: /etc/haproxy/haproxy.cfg
    dns: 127.0.0.11
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]